modLoader = "javafml"
loaderVersion = "[38,50)"
#issueTrackerURL = ""
license = "MIT License"

[[mods]]
modId = "paragraphs"
version = "${version}"
displayName = "Paragraphs Reforged"
authors = "donmor"
description = '''
Mod that allows you to write paragraphs (section signs).
'''
itemIcon = "minecraft:oak_sign"
updateJSONURL = "https://raw.githubusercontent.com/donmor/paragraphs-reforged/refs/heads/1.20.1/versions.json"
#logoFile = ""

[[dependencies.paragraphs]]
modId = "forge"
mandatory = true
versionRange = "[38,50)"
ordering = "NONE"
side = "BOTH"

[[dependencies.paragraphs]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,1.20.5)"
ordering = "NONE"
side = "BOTH"

[modproperties.paragraphs]
    catalogueImageIcon="assets/paragraphs/icon.png"
